## Project Description: Next Word Prediction Using LSTM
#### Project Overview:

This project aims to develop a deep learning model for predicting the next word in a given sequence of words. The model is built using Long Short-Term Memory (LSTM) networks, which are well-suited for sequence prediction tasks. The project includes the following steps:

1- Data Collection: We use the text of Shakespeare's "macbeth" as our dataset. This rich, complex text provides a good challenge for our model.
[https://www.nltk.org/book/ch02.html](https://www.nltk.org/book/ch02.html)

2- Data Preprocessing: The text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. The sequences are then split into training and testing sets.

3- Model Building: An LSTM model is constructed with an embedding layer, two LSTM layers, and a dense output layer with a softmax activation function to predict the probability of the next word.

4- Model Training: The model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The model is evaluated using a set of example sentences to test its ability to predict the next word accurately.

6- Deployment: A Streamlit web application is developed to allow users to input a sequence of words and get the predicted next word in real-time.

In [ ]:
import nltk
nltk.download('gutenberg')
data = nltk.corpus.gutenberg.raw('shakespeare-macbeth.txt')

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.


In [ ]:
with open('shakespeare-macbeth.txt','w') as file:
  file.write(data)


In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [ ]:
with open('shakespeare-macbeth.txt', 'r') as file:
  text = file.read().lower()

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

In [ ]:
total_words = len(tokenizer.word_index)+1
total_words

3553

In [ ]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'a': 6,
 'that': 7,
 'my': 8,
 'you': 9,
 'in': 10,
 'is': 11,
 'not': 12,
 'it': 13,
 'with': 14,
 'his': 15,
 'be': 16,
 'macb': 17,
 'your': 18,
 'our': 19,
 'haue': 20,
 'but': 21,
 'me': 22,
 'he': 23,
 'for': 24,
 'what': 25,
 'this': 26,
 'all': 27,
 'so': 28,
 'him': 29,
 'as': 30,
 'thou': 31,
 'we': 32,
 'enter': 33,
 'which': 34,
 'are': 35,
 'will': 36,
 'they': 37,
 'shall': 38,
 'no': 39,
 'then': 40,
 'macbeth': 41,
 'their': 42,
 'thee': 43,
 'vpon': 44,
 'on': 45,
 'macd': 46,
 'from': 47,
 'yet': 48,
 'thy': 49,
 'vs': 50,
 'come': 51,
 'king': 52,
 'now': 53,
 'at': 54,
 'hath': 55,
 'more': 56,
 'by': 57,
 'good': 58,
 'rosse': 59,
 'them': 60,
 'lady': 61,
 'would': 62,
 'time': 63,
 'was': 64,
 'do': 65,
 'who': 66,
 'like': 67,
 'her': 68,
 'if': 69,
 'should': 70,
 'did': 71,
 'when': 72,
 'there': 73,
 'say': 74,
 'were': 75,
 'where': 76,
 'doe': 77,
 'lord': 78,
 'make': 79,
 'or': 80,
 '1': 81,
 'must': 82,

In [ ]:
input_sequence = []

for line in text.split('\n'):
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequence.append(n_gram_sequence)


In [ ]:
input_sequence

[[1, 885],
 [1, 885, 4],
 [1, 885, 4, 41],
 [1, 885, 4, 41, 57],
 [1, 885, 4, 41, 57, 1388],
 [1, 885, 4, 41, 57, 1388, 1389],
 [1, 885, 4, 41, 57, 1388, 1389, 1390],
 [418, 1391],
 [418, 1391, 1392],
 [418, 1391, 1392, 419],
 [270, 2],
 [270, 2, 886],
 [270, 2, 886, 33],
 [270, 2, 886, 33, 196],
 [270, 2, 886, 33, 196, 298],
 [81, 72],
 [81, 72, 38],
 [81, 72, 38, 32],
 [81, 72, 38, 32, 196],
 [81, 72, 38, 32, 196, 336],
 [81, 72, 38, 32, 196, 336, 131],
 [10, 270],
 [10, 270, 886],
 [10, 270, 886, 80],
 [10, 270, 886, 80, 10],
 [10, 270, 886, 80, 10, 1393],
 [128, 72],
 [128, 72, 1],
 [128, 72, 1, 1394],
 [128, 72, 1, 1394, 1395],
 [128, 72, 1, 1394, 1395, 84],
 [72, 1],
 [72, 1, 1396],
 [72, 1, 1396, 365],
 [72, 1, 1396, 365, 2],
 [72, 1, 1396, 365, 2, 887],
 [135, 7],
 [135, 7, 36],
 [135, 7, 36, 16],
 [135, 7, 36, 16, 172],
 [135, 7, 36, 16, 172, 1],
 [135, 7, 36, 16, 172, 1, 299],
 [135, 7, 36, 16, 172, 1, 299, 4],
 [135, 7, 36, 16, 172, 1, 299, 4, 666],
 [81, 76],
 [81, 76, 1],


In [ ]:
max_sequence_len =  max(len(x) for x in input_sequence)
max_sequence_len

14

In [ ]:
input_sequence = np.array(pad_sequences(input_sequence,max_sequence_len,dtype='int32'))

In [ ]:
input_sequence

array([[   0,    0,    0, ...,    0,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4],
       [   0,    0,    0, ...,  885,    4,   41],
       ...,
       [   0,    0,    0, ..., 3552,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4],
       [   0,    0,    0, ...,  885,    4,   41]], dtype=int32)

In [ ]:
x,y = input_sequence[:,:-1], input_sequence[:,-1]

In [ ]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4],
       ...,
       [   0,    0,    0, ...,    0, 3552,    1],
       [   0,    0,    0, ..., 3552,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4]], dtype=int32)

In [ ]:
y

array([885,   4,  41, ..., 885,   4,  41], dtype=int32)

In [ ]:
import tensorflow as tf
y = tf.keras.utils.to_categorical(y, num_classes = total_words)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

model = Sequential()
model.add(Embedding(total_words,100, input_length=max_sequence_len-1))
model.add(LSTM(150, return_sequences= True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='loss', patience=3, restore_best_weights=True)
model.fit(x,y, epochs=500, verbose=1, callbacks=[early_stopping])

Epoch 1/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.3302 - loss: 3.2124
Epoch 2/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.3320 - loss: 3.1839
Epoch 3/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.3417 - loss: 3.1239
Epoch 4/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3515 - loss: 3.0696
Epoch 5/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.3624 - loss: 3.0073
Epoch 6/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.3655 - loss: 2.9772
Epoch 7/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3783 - loss: 2.9193
Epoch 8/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.3922 - loss: 2.8432
Epoch 9/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.3907 - loss: 2.8278
Epoch 10/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.3994 - loss: 2.7758
Epoch 11/500
477/477 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.4131 - loss: 2.7205
Epoch 12/500
477/477 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
def predict_the_next_word(seed_text, next_words=1):
  for _ in range(next_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding="pre")
    predicted = np.argmax(model.predict(token_list, verbose=0), axis=-1)
    output_word = ""
    for words, index in tokenizer.word_index.items():
      if index == predicted:
        output_word = words
        break

    seed_text +=" "+ output_word

    return seed_text


In [ ]:
print(predict_next_word("He", next_words=3))

He hath a heauenly


In [ ]:
model.save("next_word_predection_LSTM.h5")

In [ ]:
import pickle

with open('tokenizer.h5', 'wb') as handel:
  pickle.dump(tokenizer, handel, protocol=pickle.HIGHEST_PROTOCOL)